# Generated by Django 4.1.7 on 2023-02-19 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(max_length=5000)),
                ('content', models.TextField(max_length=10000)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2023, 2, 19, 23, 13, 39, 448500))),
                ('author', models.CharField(max_length=250)),
                ('total_likes', models.IntegerField()),
            ],
        ),
    ]
